// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: api/stock_market_api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StockMarketServiceClient is the client API for StockMarketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StockMarketServiceClient interface {
	FindStock(ctx context.Context, in *StockName, opts ...grpc.CallOption) (*Stock, error)
}

type stockMarketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStockMarketServiceClient(cc grpc.ClientConnInterface) StockMarketServiceClient {
	return &stockMarketServiceClient{cc}
}

func (c *stockMarketServiceClient) FindStock(ctx context.Context, in *StockName, opts ...grpc.CallOption) (*Stock, error) {
	out := new(Stock)
	err := c.cc.Invoke(ctx, "/api.StockMarketService/FindStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockMarketServiceServer is the server API for StockMarketService service.
// All implementations must embed UnimplementedStockMarketServiceServer
// for forward compatibility
type StockMarketServiceServer interface {
	FindStock(context.Context, *StockName) (*Stock, error)
	mustEmbedUnimplementedStockMarketServiceServer()
}

// UnimplementedStockMarketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStockMarketServiceServer struct {
}

func (UnimplementedStockMarketServiceServer) FindStock(context.Context, *StockName) (*Stock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindStock not implemented")
}
func (UnimplementedStockMarketServiceServer) mustEmbedUnimplementedStockMarketServiceServer() {}

// UnsafeStockMarketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StockMarketServiceServer will
// result in compilation errors.
type UnsafeStockMarketServiceServer interface {
	mustEmbedUnimplementedStockMarketServiceServer()
}

func RegisterStockMarketServiceServer(s grpc.ServiceRegistrar, srv StockMarketServiceServer) {
	s.RegisterService(&StockMarketService_ServiceDesc, srv)
}

func _StockMarketService_FindStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StockName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockMarketServiceServer).FindStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.StockMarketService/FindStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockMarketServiceServer).FindStock(ctx, req.(*StockName))
	}
	return interceptor(ctx, in, info, handler)
}

// StockMarketService_ServiceDesc is the grpc.ServiceDesc for StockMarketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StockMarketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.StockMarketService",
	HandlerType: (*StockMarketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindStock",
			Handler:    _StockMarketService_FindStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/stock_market_api.proto",
}
