// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/stock_market_api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Period int32

const (
	Period_HOUR Period = 0
	Period_DAY  Period = 1
	Period_WEEK Period = 2
	Period_ALL  Period = 3
)

var Period_name = map[int32]string{
	0: "HOUR",
	1: "DAY",
	2: "WEEK",
	3: "ALL",
}

var Period_value = map[string]int32{
	"HOUR": 0,
	"DAY":  1,
	"WEEK": 2,
	"ALL":  3,
}

func (x Period) String() string {
	return proto.EnumName(Period_name, int32(x))
}

func (Period) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ae39547e7469637, []int{0}
}

type UserId struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ae39547e7469637, []int{0}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type StockRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId               *UserId  `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockRequest) Reset()         { *m = StockRequest{} }
func (m *StockRequest) String() string { return proto.CompactTextString(m) }
func (*StockRequest) ProtoMessage()    {}
func (*StockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ae39547e7469637, []int{1}
}

func (m *StockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockRequest.Unmarshal(m, b)
}
func (m *StockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockRequest.Marshal(b, m, deterministic)
}
func (m *StockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockRequest.Merge(m, src)
}
func (m *StockRequest) XXX_Size() int {
	return xxx_messageInfo_StockRequest.Size(m)
}
func (m *StockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StockRequest proto.InternalMessageInfo

func (m *StockRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StockRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *StockRequest) GetUserId() *UserId {
	if m != nil {
		return m.UserId
	}
	return nil
}

type Stock struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stock) Reset()         { *m = Stock{} }
func (m *Stock) String() string { return proto.CompactTextString(m) }
func (*Stock) ProtoMessage()    {}
func (*Stock) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ae39547e7469637, []int{2}
}

func (m *Stock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stock.Unmarshal(m, b)
}
func (m *Stock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stock.Marshal(b, m, deterministic)
}
func (m *Stock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stock.Merge(m, src)
}
func (m *Stock) XXX_Size() int {
	return xxx_messageInfo_Stock.Size(m)
}
func (m *Stock) XXX_DiscardUnknown() {
	xxx_messageInfo_Stock.DiscardUnknown(m)
}

var xxx_messageInfo_Stock proto.InternalMessageInfo

func (m *Stock) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stock) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type StockChanges struct {
	Stock                *Stock   `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	OldPrice             float64  `protobuf:"fixed64,2,opt,name=oldPrice,proto3" json:"oldPrice,omitempty"`
	CurrentPrice         float64  `protobuf:"fixed64,3,opt,name=currentPrice,proto3" json:"currentPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StockChanges) Reset()         { *m = StockChanges{} }
func (m *StockChanges) String() string { return proto.CompactTextString(m) }
func (*StockChanges) ProtoMessage()    {}
func (*StockChanges) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ae39547e7469637, []int{3}
}

func (m *StockChanges) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StockChanges.Unmarshal(m, b)
}
func (m *StockChanges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StockChanges.Marshal(b, m, deterministic)
}
func (m *StockChanges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockChanges.Merge(m, src)
}
func (m *StockChanges) XXX_Size() int {
	return xxx_messageInfo_StockChanges.Size(m)
}
func (m *StockChanges) XXX_DiscardUnknown() {
	xxx_messageInfo_StockChanges.DiscardUnknown(m)
}

var xxx_messageInfo_StockChanges proto.InternalMessageInfo

func (m *StockChanges) GetStock() *Stock {
	if m != nil {
		return m.Stock
	}
	return nil
}

func (m *StockChanges) GetOldPrice() float64 {
	if m != nil {
		return m.OldPrice
	}
	return 0
}

func (m *StockChanges) GetCurrentPrice() float64 {
	if m != nil {
		return m.CurrentPrice
	}
	return 0
}

type GetStocksResponse struct {
	Stocks               []*Stock `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStocksResponse) Reset()         { *m = GetStocksResponse{} }
func (m *GetStocksResponse) String() string { return proto.CompactTextString(m) }
func (*GetStocksResponse) ProtoMessage()    {}
func (*GetStocksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ae39547e7469637, []int{4}
}

func (m *GetStocksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStocksResponse.Unmarshal(m, b)
}
func (m *GetStocksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStocksResponse.Marshal(b, m, deterministic)
}
func (m *GetStocksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStocksResponse.Merge(m, src)
}
func (m *GetStocksResponse) XXX_Size() int {
	return xxx_messageInfo_GetStocksResponse.Size(m)
}
func (m *GetStocksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStocksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStocksResponse proto.InternalMessageInfo

func (m *GetStocksResponse) GetStocks() []*Stock {
	if m != nil {
		return m.Stocks
	}
	return nil
}

type GetPortfolioChangesRequest struct {
	UserId               *UserId  `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Period               Period   `protobuf:"varint,2,opt,name=period,proto3,enum=api.Period" json:"period,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPortfolioChangesRequest) Reset()         { *m = GetPortfolioChangesRequest{} }
func (m *GetPortfolioChangesRequest) String() string { return proto.CompactTextString(m) }
func (*GetPortfolioChangesRequest) ProtoMessage()    {}
func (*GetPortfolioChangesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ae39547e7469637, []int{5}
}

func (m *GetPortfolioChangesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortfolioChangesRequest.Unmarshal(m, b)
}
func (m *GetPortfolioChangesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortfolioChangesRequest.Marshal(b, m, deterministic)
}
func (m *GetPortfolioChangesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortfolioChangesRequest.Merge(m, src)
}
func (m *GetPortfolioChangesRequest) XXX_Size() int {
	return xxx_messageInfo_GetPortfolioChangesRequest.Size(m)
}
func (m *GetPortfolioChangesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortfolioChangesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortfolioChangesRequest proto.InternalMessageInfo

func (m *GetPortfolioChangesRequest) GetUserId() *UserId {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *GetPortfolioChangesRequest) GetPeriod() Period {
	if m != nil {
		return m.Period
	}
	return Period_HOUR
}

type GetPortfolioChangesResponse struct {
	Stocks               []*StockChanges `protobuf:"bytes,1,rep,name=stocks,proto3" json:"stocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetPortfolioChangesResponse) Reset()         { *m = GetPortfolioChangesResponse{} }
func (m *GetPortfolioChangesResponse) String() string { return proto.CompactTextString(m) }
func (*GetPortfolioChangesResponse) ProtoMessage()    {}
func (*GetPortfolioChangesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ae39547e7469637, []int{6}
}

func (m *GetPortfolioChangesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPortfolioChangesResponse.Unmarshal(m, b)
}
func (m *GetPortfolioChangesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPortfolioChangesResponse.Marshal(b, m, deterministic)
}
func (m *GetPortfolioChangesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPortfolioChangesResponse.Merge(m, src)
}
func (m *GetPortfolioChangesResponse) XXX_Size() int {
	return xxx_messageInfo_GetPortfolioChangesResponse.Size(m)
}
func (m *GetPortfolioChangesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPortfolioChangesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPortfolioChangesResponse proto.InternalMessageInfo

func (m *GetPortfolioChangesResponse) GetStocks() []*StockChanges {
	if m != nil {
		return m.Stocks
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Period", Period_name, Period_value)
	proto.RegisterType((*UserId)(nil), "api.UserId")
	proto.RegisterType((*StockRequest)(nil), "api.StockRequest")
	proto.RegisterType((*Stock)(nil), "api.Stock")
	proto.RegisterType((*StockChanges)(nil), "api.StockChanges")
	proto.RegisterType((*GetStocksResponse)(nil), "api.GetStocksResponse")
	proto.RegisterType((*GetPortfolioChangesRequest)(nil), "api.GetPortfolioChangesRequest")
	proto.RegisterType((*GetPortfolioChangesResponse)(nil), "api.GetPortfolioChangesResponse")
}

func init() { proto.RegisterFile("api/stock_market_api.proto", fileDescriptor_0ae39547e7469637) }

var fileDescriptor_0ae39547e7469637 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0xc5, 0x38, 0xb8, 0x64, 0x88, 0x22, 0xb2, 0x95, 0x10, 0x72, 0x0e, 0x45, 0xdb, 0x4b, 0x5a,
	0x29, 0xb6, 0x04, 0x87, 0x48, 0xbd, 0xd1, 0x14, 0x25, 0x55, 0xd3, 0x16, 0x39, 0x8a, 0xaa, 0xe6,
	0x82, 0x16, 0x3c, 0xc0, 0x0a, 0xdb, 0xbb, 0x5d, 0x2f, 0x54, 0xe9, 0x47, 0xf6, 0x9b, 0x2a, 0xaf,
	0xd7, 0x09, 0x4d, 0xc3, 0xa1, 0xb9, 0x79, 0xe7, 0xbd, 0x79, 0xf3, 0xe6, 0x79, 0xc0, 0x67, 0x92,
	0x87, 0xb9, 0x16, 0xb3, 0xd5, 0x24, 0x65, 0x6a, 0x85, 0x7a, 0xc2, 0x24, 0x0f, 0xa4, 0x12, 0x5a,
	0x10, 0x97, 0x49, 0xee, 0x1f, 0x2f, 0x84, 0x58, 0x24, 0x18, 0x9a, 0xd2, 0x74, 0x3d, 0x0f, 0x31,
	0x95, 0xfa, 0xae, 0x64, 0xd0, 0x2e, 0x78, 0x37, 0x39, 0xaa, 0x8f, 0x31, 0x39, 0x84, 0x3a, 0x8f,
	0xbb, 0x4e, 0xcf, 0x39, 0x69, 0x44, 0x75, 0x1e, 0xd3, 0x09, 0x1c, 0x5c, 0x17, 0xaa, 0x11, 0xfe,
	0x58, 0x63, 0xae, 0x09, 0x81, 0xbd, 0x8c, 0xa5, 0x68, 0x18, 0xfb, 0x91, 0xf9, 0x26, 0x1d, 0xf0,
	0x58, 0x2a, 0xd6, 0x99, 0xee, 0xd6, 0x4d, 0x9f, 0x7d, 0x91, 0xd7, 0xe0, 0xad, 0x8d, 0x6a, 0xd7,
	0xed, 0x39, 0x27, 0xad, 0x7e, 0x2b, 0x28, 0x3c, 0x95, 0x83, 0x22, 0x0b, 0xd1, 0x01, 0x34, 0xcc,
	0x80, 0xff, 0x51, 0xa6, 0xd2, 0xba, 0x3a, 0x5f, 0xb2, 0x6c, 0x81, 0x39, 0xe9, 0x41, 0xc3, 0xec,
	0x6e, 0x9a, 0x5b, 0x7d, 0x30, 0x83, 0x4a, 0xdf, 0x25, 0x40, 0x7c, 0x68, 0x8a, 0x24, 0x1e, 0x2b,
	0x3e, 0x43, 0xa3, 0xe5, 0x44, 0xf7, 0x6f, 0x42, 0xe1, 0x60, 0xb6, 0x56, 0x0a, 0x33, 0x5d, 0xe2,
	0xae, 0xc1, 0xff, 0xaa, 0xd1, 0x33, 0x38, 0xba, 0x40, 0x6d, 0x24, 0xf3, 0x08, 0x73, 0x29, 0xb2,
	0xbc, 0x68, 0xf4, 0x8c, 0x7a, 0xde, 0x75, 0x7a, 0xee, 0xa3, 0xb9, 0x16, 0xa1, 0x73, 0xf0, 0x2f,
	0x50, 0x8f, 0x85, 0xd2, 0x73, 0x91, 0x70, 0x61, 0x1d, 0x57, 0x71, 0x3e, 0x44, 0xe4, 0xec, 0x8c,
	0xa8, 0x20, 0x49, 0x54, 0x5c, 0xc4, 0xc6, 0xf9, 0xa1, 0x25, 0x8d, 0x4d, 0x29, 0xb2, 0x10, 0xbd,
	0x84, 0xe3, 0x27, 0xe7, 0x58, 0xab, 0x6f, 0x1e, 0x59, 0x3d, 0x7a, 0xb0, 0x5a, 0x51, 0x2d, 0xe1,
	0x6d, 0x00, 0x5e, 0xa9, 0x4d, 0x9a, 0xb0, 0x77, 0xf9, 0xf5, 0x26, 0x6a, 0xd7, 0xc8, 0x0b, 0x70,
	0x3f, 0x0c, 0xbf, 0xb7, 0x9d, 0xa2, 0xf4, 0x6d, 0x34, 0xfa, 0xd4, 0xae, 0x17, 0xa5, 0xe1, 0xd5,
	0x55, 0xdb, 0xed, 0xff, 0xae, 0x03, 0x31, 0x42, 0x9f, 0xcd, 0xe1, 0x5d, 0xa3, 0xda, 0x14, 0xa9,
	0x0e, 0x00, 0xce, 0x15, 0x32, 0x8d, 0xc5, 0x36, 0xa4, 0x13, 0x94, 0xf7, 0x17, 0x54, 0xf7, 0x17,
	0x8c, 0x8a, 0xfb, 0xf3, 0xb7, 0x17, 0xa6, 0x35, 0xd2, 0x87, 0xfd, 0xfb, 0x98, 0xc9, 0x36, 0xe6,
	0x77, 0xcc, 0xe3, 0x9f, 0x7f, 0x40, 0x6b, 0xe4, 0x0c, 0x9a, 0xc3, 0x38, 0x2e, 0x8f, 0x68, 0x6b,
	0x2d, 0x1b, 0xb1, 0xbf, 0x63, 0x32, 0xad, 0x91, 0x77, 0xd0, 0x8a, 0x30, 0x15, 0x1b, 0x7c, 0x46,
	0xef, 0x2d, 0xbc, 0x7c, 0x22, 0x6e, 0xf2, 0xaa, 0x72, 0xb9, 0xe3, 0x87, 0xfb, 0xbd, 0xdd, 0x84,
	0x6a, 0xa1, 0xf7, 0xe1, 0xed, 0xe9, 0x82, 0xeb, 0x84, 0x4d, 0x03, 0xf1, 0x4b, 0x64, 0x41, 0x8c,
	0x9b, 0x70, 0xb6, 0xe4, 0x49, 0x72, 0xf7, 0x85, 0xcf, 0x56, 0xe1, 0x52, 0xa4, 0xf8, 0x53, 0xa8,
	0xd5, 0x69, 0x3f, 0x94, 0xab, 0x45, 0xc8, 0x24, 0x9f, 0x7a, 0xc6, 0xde, 0xe0, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x8e, 0x03, 0x66, 0x08, 0x05, 0x04, 0x00, 0x00,
}
