// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: api/stock_market_api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StockName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *StockName) Reset() {
	*x = StockName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_stock_market_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StockName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockName) ProtoMessage() {}

func (x *StockName) ProtoReflect() protoreflect.Message {
	mi := &file_api_stock_market_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockName.ProtoReflect.Descriptor instead.
func (*StockName) Descriptor() ([]byte, []int) {
	return file_api_stock_market_api_proto_rawDescGZIP(), []int{0}
}

func (x *StockName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Stock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *StockName `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Stock) Reset() {
	*x = Stock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_stock_market_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_api_stock_market_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_api_stock_market_api_proto_rawDescGZIP(), []int{1}
}

func (x *Stock) GetName() *StockName {
	if x != nil {
		return x.Name
	}
	return nil
}

var File_api_stock_market_api_proto protoreflect.FileDescriptor

var file_api_stock_market_api_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x5f, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70,
	0x69, 0x22, 0x1f, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x2b, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32,
	0x3f, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64, 0x53, 0x74, 0x6f,
	0x63, 0x6b, 0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x1a, 0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x22, 0x00,
	0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e,
	0x64, 0x65, 0x76, 0x2f, 0x63, 0x68, 0x69, 0x6c, 0x6c, 0x79, 0x4e, 0x69, 0x63, 0x6b, 0x2f, 0x68,
	0x6f, 0x6d, 0x65, 0x77, 0x6f, 0x72, 0x6b, 0x2d, 0x32, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_stock_market_api_proto_rawDescOnce sync.Once
	file_api_stock_market_api_proto_rawDescData = file_api_stock_market_api_proto_rawDesc
)

func file_api_stock_market_api_proto_rawDescGZIP() []byte {
	file_api_stock_market_api_proto_rawDescOnce.Do(func() {
		file_api_stock_market_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_stock_market_api_proto_rawDescData)
	})
	return file_api_stock_market_api_proto_rawDescData
}

var file_api_stock_market_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_stock_market_api_proto_goTypes = []interface{}{
	(*StockName)(nil), // 0: api.StockName
	(*Stock)(nil),     // 1: api.Stock
}
var file_api_stock_market_api_proto_depIdxs = []int32{
	0, // 0: api.Stock.name:type_name -> api.StockName
	0, // 1: api.StockMarketService.FindStock:input_type -> api.StockName
	1, // 2: api.StockMarketService.FindStock:output_type -> api.Stock
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_stock_market_api_proto_init() }
func file_api_stock_market_api_proto_init() {
	if File_api_stock_market_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_stock_market_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StockName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_stock_market_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_stock_market_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_stock_market_api_proto_goTypes,
		DependencyIndexes: file_api_stock_market_api_proto_depIdxs,
		MessageInfos:      file_api_stock_market_api_proto_msgTypes,
	}.Build()
	File_api_stock_market_api_proto = out.File
	file_api_stock_market_api_proto_rawDesc = nil
	file_api_stock_market_api_proto_goTypes = nil
	file_api_stock_market_api_proto_depIdxs = nil
}
